# core packages
brew "autojump"
brew "coreutils"
brew "duti"
brew "ffmpeg"
brew "fx"
brew "git-cal"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "rbenv"
brew "rbenv-gemset"
brew "ripgrep"
brew "ruby-build"
brew "terminal-notifier"
brew "tmux"
brew "tree"
brew "wget"

cask "monitorcontrol" # 1.7.0
cask "provisionql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "suspicious-package"
